### ISSUE TITLE
[error] Cannot connect to printer, permission denied

### ISSUE THREAD

**Issue by cenklar** [markwal/OctoPrint-GPX#42]
Hi I have installed OctoPrint and OctoPrint-GPX in an old laptop running Ubuntu, but I'm not able to connect to my printer (a makerbot clone). Octoprint throws me this error: [Errno 13] Permission denied: '/dev/ttyACM0'

what can I do to solve the issue? thanks in advance.

Here is the complete info OctoPrint threw out:

2017-03-02 19:17:06,924 - octoprint.plugins.GPX - INFO - Connecting through x3g.
2017-03-02 19:17:06,925 - octoprint.plugins.GPX - INFO - GPXPrinter created, port: /dev/ttyACM0, baudrate: 115200
Error opening port: Permission denied
2017-03-02 19:17:06,927 - octoprint.plugins.GPX - INFO - gpx.connect raised exception = [Errno 13] Permission denied: '/dev/ttyACM0'
2017-03-02 19:17:06,928 - octoprint.plugins.GPX - INFO - Failed to connect to x3g e = [Errno 13] Permission denied: '/dev/ttyACM0'.
2017-03-02 19:17:06,937 - octoprint.util.comm - ERROR - Unexpected error while connecting to serial port: /dev/ttyACM0 OSError: '[Errno 13] Permission denied: '/dev/ttyACM0'' @ comm.py:_openSerial:1694 (hook GPX)
Traceback (most recent call last):
  File "/home/ubuntu/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.1-py2.7.egg/octoprint/util/comm.py", line 1694, in _openSerial
    serial_obj = factory(self, self._port, self._baudrate, settings().getFloat(["serial", "timeout", "connection"]))
  File "/home/ubuntu/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_GPX/__init__.py", line 117, in serial_factory
    self.printer = GpxPrinter(self, port, baudrate, timeout)
  File "/home/ubuntu/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_GPX/gpxprinter.py", line 42, in __init__
    self._settings.get_boolean(["verbose"])))
OSError: [Errno 13] Permission denied: '/dev/ttyACM0'
2017-03-02 19:17:08,624 - octoprint.plugins.GPX - INFO - Connecting through x3g.
2017-03-02 19:17:08,625 - octoprint.plugins.GPX - INFO - GPXPrinter created, port: /dev/ttyACM0, baudrate: 115200
Error opening port: Permission denied
2017-03-02 19:17:08,627 - octoprint.plugins.GPX - INFO - gpx.connect raised exception = [Errno 13] Permission denied: '/dev/ttyACM0'
2017-03-02 19:17:08,633 - octoprint.plugins.GPX - INFO - Failed to connect to x3g e = [Errno 13] Permission denied: '/dev/ttyACM0'.
2017-03-02 19:17:08,639 - octoprint.util.comm - ERROR - Unexpected error while connecting to serial port: /dev/ttyACM0 OSError: '[Errno 13] Permission denied: '/dev/ttyACM0'' @ comm.py:_openSerial:1694 (hook GPX)
Traceback (most recent call last):
  File "/home/ubuntu/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.1-py2.7.egg/octoprint/util/comm.py", line 1694, in _openSerial
    serial_obj = factory(self, self._port, self._baudrate, settings().getFloat(["serial", "timeout", "connection"]))
  File "/home/ubuntu/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_GPX/__init__.py", line 117, in serial_factory
    self.printer = GpxPrinter(self, port, baudrate, timeout)
  File "/home/ubuntu/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_GPX/gpxprinter.py", line 42, in __init__
    self._settings.get_boolean(["verbose"])))
OSError: [Errno 13] Permission denied: '/dev/ttyACM0'

**Comment by markwal** [comment]
Hmmm...  What does the following say:

```
ls -la /dev/ttyACM0
```

On my octopi image, it looks like the user that the OctoPrint daemon is running under has to be part of the dialout group.  Perhaps that's the same for you as well?
