### ISSUE TITLE
Haven't been able to print x3g files for ages ...

### ISSUE THREAD

**Issue by jrpmedia** [markwal/OctoPrint-GPX#61]
Opps sorry, pressed Post too early...

I have not been able to get .x3g files to print to my FlashForge Creator Pro's [6 of them] using OctoPrint on Pi B's, for ages...

I go to print and get:
Offline (Error: TypeError: 'must be string without null bytes, not str' @ comm.py:_do_send_without_checksum:30

**Comment by jrpmedia** [comment]
Changing monitoring state from "Operational" to "Printing"
Send: N0 M110 N0*125
Recv: ok
Send: (@build "Woggle_-_Plain")
Recv: ok
Send: N1 M136 (Woggle_-_Plain)*65
Recv: ok
Send: N2 G92 X0 Y0 Z0 A0 B0*88
Recv: ok
Send: ?\x00\x00\x00\x00FlashPrint\x00?\x00??\x00\x1f\x02-\x00?\x00
Unexpected error while writing to serial port: TypeError: 'must be string without null bytes, not str' @ comm.py:_do_send_without_checksum:3005
Changing monitoring state from "Printing" to "Offline (Error: TypeError: 'must be string without null bytes, not str' @ comm.py:_do_send_without_checksum:3005)"
Connection closed, closing down monitor

**Comment by jrpmedia** [comment]
OctoPrint 1.3.8 running on OctoPi 0.13.0

**Comment by jrpmedia** [comment]
Recv: // echo: (line 16) Semantic warning: T0 cannot select non-existant extruder
Recv: // echo: (line 16) Semantic warning: M140 cannot select non-existant heated build platform
Send: N17 M134 T0*87
Recv: ok
Send: N18 M104 S230 T0*25
Recv: // echo: (line 17) Semantic warning: T0 cannot select non-existant extruder
Recv: // echo: (line 17) Semantic warning: M134 cannot select non-existant heated build platform
Recv: ok
Recv: // echo: (line 18) Semantic warning: T0 cannot select non-existant extruder
Send: N19 M133 T0*94

**Comment by jrpmedia** [comment]
I changed the GPX settings vales.
I rebooted everything.
I changed the GPX settings back to original.
I rebooted.
All is working again :-)

QED: Stuck GPX settings?

**Comment by ErroneousBosch** [comment]
Same error, same printer, though no luck with messing with settings:
`Offline (Error: TypeError: 'argument 1 must be string without null bytes, not str' @ comm.py:_do_send_without_checksum:3450)`

```
2019-10-28 18:45:03,927 - octoprint.util.comm - INFO - M110 detected, setting cu                             rrent line number to 0
2019-10-28 18:45:03,957 - octoprint.util.comm - INFO - Changing monitoring state                              from "Starting" to "Printing"
2019-10-28 18:45:03,965 - octoprint.util.comm - ERROR - Unexpected error while w                             riting to serial port
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py                             ", line 3450, in _do_send_without_checksum
    result = self._serial.write(to_send)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_GPX/gpxprint                             er.py", line 131, in write
    self._append(gpx.write("%s" % data))
TypeError: argument 1 must be string without null bytes, not str
2019-10-28 18:45:04,029 - octoprint.util.comm - INFO - Changing monitoring state                              from "Printing" to "Offline (Error: TypeError: 'argument 1 must be string witho                             ut null bytes, not str' @ comm.py:_do_send_without_checksum:3450)"
2019-10-28 18:45:04,658 - octoprint.plugins.tracking - INFO - Sent tracking even                             t print_started, payload: {'origin': 'local', 'file': 'dea61bcd89af723af3c7b7db7                             5ce1e6cc2857f1f'}
2019-10-28 18:45:05,364 - octoprint.plugins.tracking - INFO - Sent tracking even                             t print_failed, payload: {'origin': 'local', 'reason': 'error', 'commerror_text'                             : "TypeError: 'argument 1 must be string without null bytes, not str' @ comm.py:                             _do_send_without_checksum:3450", 'file': 'dea61bcd89af723af3c7b7db75ce1e6cc2857f                             1f'}
```

**Comment by ErroneousBosch** [comment]
I also get the following when trying to upload to SD:
`Offline (Error: IOError: 'Command not supported or recognized' @ comm.py:_do_send_without_checksum:3450)`

```2019-10-28 18:50:48,713 - octoprint.util.comm - ERROR - Unexpected error while writing to serial port
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 3450, in _do_send_without_checksum
    result = self._serial.write(to_send)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_GPX/gpxprinter.py", line 131, in write
    self._append(gpx.write("%s" % data))
IOError: Command not supported or recognized
2019-10-28 18:50:48,775 - octoprint.util.comm - INFO - Changing monitoring state from "Operational" to "Offline (Error: IOError: 'Command not supported or recognized' @ comm.py:_do_send_without_checksum:3450)"
```

**Comment by ErroneousBosch** [comment]
@jrpmedia What settings did you finally get working?

**Comment by ErroneousBosch** [comment]
Ignore mine, I apparently can't read the documentation about x3g files.

**Comment by markwal** [comment]
It looks like both reports are working now.
