### ISSUE TITLE
unable to install - see following errors

### ISSUE THREAD

**Issue by ghvader** [markwal/OctoPrint-GPX#8]
Could not find any downloads that satisfy the requirement OctoPrint (from OctoPrint-GPX==0.3.13)
pi@octopi:~$ pip install https://markwal.github.io/OctoPrint/OctoPrint-GPX.tar.gz
Downloading/unpacking https://markwal.github.io/OctoPrint/OctoPrint-GPX.tar.gz
  Downloading OctoPrint-GPX.tar.gz (588Kb): 588Kb downloaded
  Running setup.py egg_info for package from https://markwal.github.io/OctoPrint/OctoPrint-GPX.tar.gz

Downloading/unpacking OctoPrint (from OctoPrint-GPX==0.3.13)
  Could not find any downloads that satisfy the requirement OctoPrint (from OctoPrint-GPX==0.3.13)
No distributions at all found for OctoPrint (from OctoPrint-GPX==0.3.13)
Storing complete log in /home/pi/.pip/pip.log
pi@octopi:~$ cat /home/pi/.pip/pip.log
Downloading/unpacking https://markwal.github.io/OctoPrint/OctoPrint-GPX.tar.gz

  Downloading from URL https://markwal.github.io/OctoPrint/OctoPrint-GPX.tar.gz
  Running setup.py egg_info for package from https://markwal.github.io/OctoPrint/OctoPrint-GPX.tar.gz

```
running egg_info
creating pip-egg-info/OctoPrint_GPX.egg-info
writing requirements to pip-egg-info/OctoPrint_GPX.egg-info/requires.txt
writing pip-egg-info/OctoPrint_GPX.egg-info/PKG-INFO
writing top-level names to pip-egg-info/OctoPrint_GPX.egg-info/top_level.txt
writing dependency_links to pip-egg-info/OctoPrint_GPX.egg-info/dependency_links.txt
writing entry points to pip-egg-info/OctoPrint_GPX.egg-info/entry_points.txt
writing manifest file 'pip-egg-info/OctoPrint_GPX.egg-info/SOURCES.txt'
warning: manifest_maker: standard file '-c' not found


reading manifest file 'pip-egg-info/OctoPrint_GPX.egg-info/SOURCES.txt'
writing manifest file 'pip-egg-info/OctoPrint_GPX.egg-info/SOURCES.txt'
```

Downloading/unpacking OctoPrint (from OctoPrint-GPX==0.3.13)

  Getting page http://pypi.python.org/simple/OctoPrint
  Could not fetch URL http://pypi.python.org/simple/OctoPrint: HTTP Error 404: Not Found
  Will skip URL http://pypi.python.org/simple/OctoPrint when looking for download links for OctoPrint (from OctoPrint-GPX==0.3.13)
  Getting page http://pypi.python.org/simple/
  URLs to search for versions for OctoPrint (from OctoPrint-GPX==0.3.13):
- http://pypi.python.org/simple/OctoPrint/
  Getting page http://pypi.python.org/simple/OctoPrint/
  Could not fetch URL http://pypi.python.org/simple/OctoPrint/: HTTP Error 404: Not Found
  Will skip URL http://pypi.python.org/simple/OctoPrint/ when looking for download links for OctoPrint (from OctoPrint-GPX==0.3.13)
  Could not find any downloads that satisfy the requirement OctoPrint (from OctoPrint-GPX==0.3.13)

No distributions at all found for OctoPrint (from OctoPrint-GPX==0.3.13)

Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 978, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 157, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)

**Comment by ghvader** [comment]
so when i first installed i didn't enable user access (my PI is on a private lan)
i re-wrote the image, started over.. enabled user access and everything works now.
i saw no plugins before. but now i saw a bunch.. and gpx installed easily.. so i'll leave this here encase anyone else has the same issue.. ENABLE USER ACCESS CONTROL :)
